//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWebAutos.WSCobroEnLineaMAPFRE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSCobroEnLineaMAPFRE.ICOBRO_TC_POS")]
    public interface ICOBRO_TC_POS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOBRO_TC_POS/COBRAR_TC", ReplyAction="http://tempuri.org/ICOBRO_TC_POS/COBRAR_TCResponse")]
        string COBRAR_TC(string INFOCOBRO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOBRO_TC_POS/COBRAR_TC", ReplyAction="http://tempuri.org/ICOBRO_TC_POS/COBRAR_TCResponse")]
        System.Threading.Tasks.Task<string> COBRAR_TCAsync(string INFOCOBRO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICOBRO_TC_POSChannel : CotizadorWebAutos.WSCobroEnLineaMAPFRE.ICOBRO_TC_POS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class COBRO_TC_POSClient : System.ServiceModel.ClientBase<CotizadorWebAutos.WSCobroEnLineaMAPFRE.ICOBRO_TC_POS>, CotizadorWebAutos.WSCobroEnLineaMAPFRE.ICOBRO_TC_POS {
        
        public COBRO_TC_POSClient() {
        }
        
        public COBRO_TC_POSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public COBRO_TC_POSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public COBRO_TC_POSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public COBRO_TC_POSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string COBRAR_TC(string INFOCOBRO) {
            return base.Channel.COBRAR_TC(INFOCOBRO);
        }
        
        public System.Threading.Tasks.Task<string> COBRAR_TCAsync(string INFOCOBRO) {
            return base.Channel.COBRAR_TCAsync(INFOCOBRO);
        }
    }
}
